# Generated by Django 5.0.14 on 2025-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_temp_password',
            field=models.BooleanField(default=False),
        ),
    ]
