# Generated by Django 5.0.14 on 2025-12-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='portraitbooking',
            name='category',
            field=models.CharField(choices=[('paintings', 'Paintings'), ('pencil', 'Pencil Drawings'), ('caricature', 'Caricatures'), ('stencil', 'Stencil Artworks'), ('mural', 'Kerala Murals')], default='paintings', max_length=50),
        ),
    ]
