# Generated by Django 5.0.14 on 2025-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_portraitbooking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraitbooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
