# Generated by Django 5.0.14 on 2025-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_portraitbooking_preferred_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraitbooking',
            name='category',
            field=models.CharField(choices=[('paintings', 'Paintings'), ('pencil', 'Pencil Drawings'), ('caricature', 'Caricatures'), ('stencil', 'Stencil Artworks')], default='paintings', max_length=50),
        ),
    ]
