# Generated by Django 5.0.14 on 2025-12-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_portraitbooking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portraitbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portraitbooking',
            name='category',
            field=models.CharField(choices=[('paintings', 'Paintings'), ('pencil', 'Pencil Drawings'), ('caricature', 'Caricatures'), ('stencil', 'Stencil Artworks'), ('pen_art', 'Pen Art'), ('ghibli_art', 'Ghibli Art')], default='paintings', max_length=50),
        ),
    ]
