# Generated by Django 5.0.14 on 2025-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_portraitbooking_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portraitbooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitbooking',
            name='category',
            field=models.CharField(choices=[('paintings', 'Paintings'), ('pencil', 'Pencil Drawings'), ('caricature', 'Caricatures'), ('stencil', 'Stencil Artworks'), ('mural', 'Kerala Mural'), ('pen_art', 'Pen Art'), ('ghibli_art', 'Ghibli Art')], default='paintings', max_length=50),
        ),
        migrations.AlterField(
            model_name='portraitbooking',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/'),
        ),
    ]
