# Generated by Django 5.2.10 on 2026-03-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_portraitbooking_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portraitbooking',
            old_name='city',
            new_name='district',
        ),
    ]
