# Generated by Django 5.2.10 on 2026-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_city_portraitbooking_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='portraitbooking',
            name='frame_type',
            field=models.CharField(blank=True, choices=[('Plastic', 'Plastic'), ('Wooden', 'Wooden'), ('Metal', 'Metal'), ('Premium Wooden', 'Premium Wooden'), ('Vintage Gold', 'Vintage Gold'), ('Matte Black', 'Matte Black')], default='', help_text='Select frame type for your portrait', max_length=50),
        ),
        migrations.AlterField(
            model_name='portraitbooking',
            name='category',
            field=models.CharField(choices=[('caricature', 'Caricature'), ('pen_art', 'Pen Art'), ('paintings', 'Painting'), ('pencil', 'Pencil Drawing'), ('stencil', 'Stencil Art')], default='paintings', max_length=50),
        ),
    ]
