# Generated by Django 5.2.10 on 2026-03-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_is_paid_order_payment_method_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='city',
            new_name='district',
        ),
    ]
