# Generated by Django 5.0.14 on 2025-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, choices=[('paintings', 'Paintings'), ('pencil', 'Pencil Drawings'), ('caricature', 'Caricatures'), ('stencil', 'Stencil Artworks'), ('mural', 'Kerala Mural'), ('pen_art', 'Pen Art')], unique=True),
        ),
    ]
