# Generated by Django 5.0.14 on 2025-12-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_name'),
    ]

    operations = [
    ]
