# Generated by Django 5.0.14 on 2025-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., 12x18 inches, A4, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('paintings', 'Paintings'), ('pencil', 'Pencil Drawings'), ('caricature', 'Caricatures'), ('stencil', 'Stencil Artworks'), ('mural', 'Kerala Mural'), ('pen_art', 'Pen Art'), ('ghibli_art', 'Ghibli Art')], max_length=100, unique=True),
        ),
    ]
