# Generated by Django 5.0.14 on 2025-12-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20251227_2058'),
        ('shop', '0005_product_size_alter_category_name'),
    ]

    operations = [
    ]
