# Generated by Django 5.2.10 on 2026-03-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20251227_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_city',
            new_name='shipping_district',
        ),
    ]
