# Generated by Django 5.0.14 on 2025-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
